name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: sxzz/workflows/.github/workflows/release.yml@69098296b6f6083ed99f38e2040f2a7238580e27 # v1.4.0
    with:
      publish: true
